channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-base=4.5.1
  - r-micropan=2.1
  - r-vegan=2.5_4
  - bioconda::bioconductor-limma=3.62.1
  - r-pheatmap=1.0.10
  - r-ggplot2=3.1.0
