channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-base=4.4.0
  - conda-forge::r-micropan=2.1
  - r-vegan=2.7_1
  - bioconda::bioconductor-limma=3.62.1
  - r-pheatmap=1.0.13
  - r-ggplot2=3.5.2
